language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
    - export PATH=$HOME/.local/bin:$PATH
    - pip install crossbar --user `whoami`

before_script:
    - composer install
    - sh tests/Crossbar/travis_install

script:
    - php tests/TestServer.php 20 & phpunit
    - sh tests/Crossbar/run_tests

